version: '0.2'
language: en
words:
  - unplugin
  - Vcode
  - lowcode
  - antv
  - echarts
  - wangEditor
  - hoverbar
ignorePaths:
  - node_modules
  - dist
  - .git
  - pnpm-lock.yaml
  - package-lock.json
  - yarn.lock
  - '*.svg'
  - '*.png'
  - '*.jpg'
  - '*.jpeg'
  - '*.gif'
